# Generated by Django 4.2.6 on 2023-11-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_city_remove_customer_email_remove_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(default="bu yerda tez orada ma'lumot bo'ladi", null=True, verbose_name="Mahsulot haqida ma'lumot"),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(default="bu yerda tez orada ma'lumot bo'ladi", null=True, verbose_name="Mahsulot haqida ma'lumot"),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(default="bu yerda tez orada ma'lumot bo'ladi", null=True, verbose_name="Mahsulot haqida ma'lumot"),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Mahsulot nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Mahsulot nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Mahsulot nomi'),
        ),
    ]
